services:
  section_field.generator.entity_generator:
    class: Tardigrades\SectionField\Generator\EntityGenerator
    arguments:
      - '@section_field.manager.doctrine.field_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.section_manager'


